// apps/workflow/app/layout.tsx
// 根布局组件
//
// 这个组件包裹所有页面，用于：
// 1. 设置 HTML 结构（lang、charset 等）
// 2. 加载全局样式
// 3. 提供全局上下文（如主题、用户状态）

import type { Metadata } from 'next';
// import { Geist, Geist_Mono } from 'next/font/google';
import { Inter } from 'next/font/google';
import './globals.css';

// 加载 Inter 字体（Google Fonts）
// subsets: ['latin'] 只加载拉丁字符，减少体积
const inter = Inter({ subsets: ['latin'] });

// 页面元数据（用于 SEO）
export const metadata: Metadata = {
  title: 'AI 工作流',
  description: '可视化 AI 工作流编排平台',
};

// 跟布局组件
export default function RootLayout({
  children,
}: Readonly<{
  // children 是当前页面的内容
  children: React.ReactNode;
}>) {
  return (
    // lang="zh-CN" 指定页面语言为中文
    <html lang="zh-CN">
      {/* 应用字体和全局样式 */}
      <body className={inter.className}>{children}</body>
    </html>
  );
}

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// });

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }
